name: nepali_utils
description: A pure dart package with collection of Nepali Utilities like Date converter, Date formatter, DateTime, Nepali Numbers, Nepali Unicode, Nepali Moments and many more.
version: 2.2.0+2
repository: https://github.com/sarbagyastha/nepali_utils
homepage: https://sarbagyastha.com.np

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: ^1.9.4
